apiVersion: apps/v1
kind: Deployment
metadata:
  name: robusta-runner
  labels:
    app: robusta-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robusta-runner
  template:
    metadata:
      labels:
        app: robusta-runner
    spec:
      serviceAccountName: robusta-runner
      containers:
      - name: runner
        image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
          - name: PLAYBOOKS_ROOT
            value: /etc/robusta/playbooks/
          - name: CONFIG_PATH
            value: /etc/robusta/config/active_playbooks.yaml
          - name: ENABLE_MANHOLE
            value: "true"
          - name: ENABLE_COLORED_LOGS
            value: "true"
          - name: LOG_LEVEL
            value: INFO
        volumeMounts:
          - name: custom-playbooks
            mountPath: /etc/robusta/playbooks/custom
          - name: playbooks-config
            mountPath: /etc/robusta/config
        lifecycle:
          preStop:
            exec:
              command: ["bash", "-c", "kill -SIGINT 1"]
      - name: grafana-renderer
        image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/grafana-renderer:4
        imagePullPolicy: Always
        securityContext:
          privileged: false
        lifecycle:
          preStop:
            exec:
              command: ["bash", "-c", "kill -SIGINT 1"]
        resources:
          limits:
            memory: "512Mi"
      volumes:
        - name: custom-playbooks
          configMap:
            name: robusta-custom-playbooks
            optional: true
        - name: playbooks-config
          configMap:
            name: robusta-config
            optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: robusta-runner
spec:
  selector:
    app: robusta-runner
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000