apiVersion: v2
name: robusta
description: Robusta Helm chart for Kubernetes
type: application

# these are set to the right value by .github/workflows/release.yaml when you do a release
version: 0.0.0
appVersion: 0.0.0

dependencies:
- name: kube-prometheus-stack
  version: 19.2.3
  condition: enablePrometheusStack
  repository: "https://prometheus-community.github.io/helm-charts"